# Generated by Django 2.0.6 on 2018-10-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('build', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('inherit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFE',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfes', to='api.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFEResult',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField()),
                ('percent', models.FloatField()),
                ('job_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfe_results', to='api.JobResult')),
                ('rfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RFE')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField()),
                ('job_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api.JobResult')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rfe',
            name='tests',
            field=models.ManyToManyField(blank=True, to='api.Test'),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_results', to='api.Product'),
        ),
    ]
