# Generated by Django 2.0.6 on 2018-10-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='jobname',
            field=models.CharField(default='<unknown>', max_length=100),
            preserve_default=False,
        ),
    ]
