# Generated by Django 2.0.8 on 2018-11-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobresult_jobname'),
    ]

    operations = [
        migrations.AddField(
            model_name='rferesult',
            name='tested',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
