# Generated by Django 2.0.8 on 2019-01-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rferesult_tested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfe',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
