# Generated by Django 2.0.6 on 2018-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicovapp', '0002_remove_product_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='build',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
