# Generated by Django 2.0.6 on 2018-07-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicovapp', '0003_jobresult_build'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfe',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='rfe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicovapp.Product'),
            preserve_default=False,
        ),
    ]
