# Generated by Django 2.0.6 on 2018-09-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicovapp', '0005_rferesult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testid',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
